### ISSUE TITLE
distance appear

### ISSUE THREAD

**Issue by sexyalee** [infinitydevelopment14/id_carwash#3]
Hello, how do I change the visual distance, so that the icon is not seen on the minimap in the distance as it appears in the following image?
![distance](https://user-images.githubusercontent.com/74865063/172032793-a37ebcc0-531b-41fb-a760-adbbacb69b06.png)
![distnace2](https://user-images.githubusercontent.com/74865063/172032825-866fdc58-3438-4f98-852d-1dbaba64f9be.png)

**Comment by isgrandson** [comment]
Sorry about that, will be fixed in new version (works in source code).

Anyways, just change SetBlipAsShortRange(blip, false) > SetBlipAsShortRange(blip, true) in the client side.
